export const car = [
  {
    id: 201,
    brand: "Toyota",
    model: "Camry",
    year: "(2024)",
    price: "28 Lakh",
    mileage: 12500,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "White",
    engine: "2.5L",
    horsepower: 203,
    seats: 5,
    doors: 4,
    location: "Delhi",
    state: "Delhi",
    country: "India",
    rating: 4.7,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80"
  },

  {
    id: 202,
    brand: "BMW",
    model: "3 Series",
    year: "(2024)",
    price: "48.5 Lakh",
    mileage: 8200,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Black",
    engine: "2.0L Turbo",
    horsepower: 255,
    seats: 5,
    doors: 4,
    location: "Mumbai",
    state: "Maharashtra",
    country: "India",
    rating: 4.8,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80"
  },

  {
    id: 203,
    brand: "Mercedes-Benz",
    model: "C-Class",
    year: "(2023)",
    price: "56 Lakh",
    mileage: 15600,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Silver",
    engine: "2.0L Turbo",
    horsepower: 255,
    seats: 5,
    doors: 4,
    location: "Bangalore",
    state: "Karnataka",
    country: "India",
    rating: 4.9,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80"
  },

  {
    id: 204,
    brand: "Audi",
    model: "A4",
    year: "(2024)",
    price: "46.5 Lakh",
    mileage: 9300,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Blue",
    engine: "2.0L TFSI",
    horsepower: 201,
    seats: 5,
    doors: 4,
    location: "Pune",
    state: "Maharashtra",
    country: "India",
    rating: 4.6,
    isAvailable: true,
    isFeatured: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQb5Ji8v8TDBvM4TC00MWQicvL9jXUdp-xhelnHaS9NnA&s=10"
  },

  {
    id: 205,
    brand: "Tesla",
    model: "Model 3",
    year: "(2024)",
    price: "52 Lakh",
    mileage: 6700,
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Red",
    engine: "Dual Motor",
    horsepower: 394,
    seats: 5,
    doors: 4,
    location: "Gurugram",
    state: "Haryana",
    country: "India",
    rating: 4.8,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnWu7WEc5VyGiNxB9wVa4yP3V1LMBoQ_yPPz57adYjmw&s=10"
  },

  {
    id: 206,
    brand: "Ford",
    model: "Mustang",
    year: "(2023)",
    price: "74 Lakh",
    mileage: 11800,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Coupe",
    color: "Red",
    engine: "5.0L V8",
    horsepower: 480,
    seats: 4,
    doors: 2,
    location: "Chandigarh",
    state: "Chandigarh",
    country: "India",
    rating: 4.9,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?auto=format&fit=crop&w=1200&q=80"
  },

  {
    id: 207,
    brand: "Honda",
    model: "City",
    year: "(2024)",
    price: "16.5 Lakh",
    mileage: 7400,
    fuelType: "Petrol",
    transmission: "CVT",
    bodyType: "Sedan",
    color: "Grey",
    engine: "1.5L",
    horsepower: 119,
    seats: 5,
    doors: 4,
    location: "Jaipur",
    state: "Rajasthan",
    country: "India",
    rating: 4.5,
    isAvailable: true,
    isFeatured: false,
    image:
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80"
  },

  {
    id: 208,
    brand: "Hyundai",
    model: "Creta",
    year: "(2024)",
    price: "18.5 Lakh",
    mileage: 5600,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "White",
    engine: "1.5L Turbo",
    horsepower: 160,
    seats: 5,
    doors: 5,
    location: "Lucknow",
    state: "Uttar Pradesh",
    country: "India",
    rating: 4.6,
    isAvailable: true,
    isFeatured: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLzEidepJwWwjTY3QIyP0MXVLow4XWgzOf5oxEjed-lQ&s=10"
  },

  {
    id: 209,
    brand: "Kia",
    model: "Seltos",
    year: "(2024)",
    price: "19.5 Lakh",
    mileage: 6100,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Black",
    engine: "1.5L Diesel",
    horsepower: 114,
    seats: 5,
    doors: 5,
    location: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    rating: 4.5,
    isAvailable: true,
    isFeatured: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxEcQQlVm7jS0_Dz9FLIebGMJfTQwRLAVbVI5_P6HF9w&s=10"
  },

  {
    id: 210,
    brand: "Mahindra",
    model: "Thar",
    year: "(2024)",
    price: "19.5 Lakh",
    mileage: 8900,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Green",
    engine: "2.2L Diesel",
    horsepower: 130,
    seats: 4,
    doors: 3,
    location: "Amritsar",
    state: "Punjab",
    country: "India",
    rating: 4.7,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZyWmOxrzDbZEgJUJE12NHMVZ2JNZBv1hyFYc3UEsmmg&s=10"
  },

  {
    id: 211,
    brand: "Range Rover",
    model: "Sport",
    year: "(2023)",
    price: "1.45 Cr",
    mileage: 14300,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Black",
    engine: "3.0L Turbo",
    horsepower: 355,
    seats: 5,
    doors: 5,
    location: "New Delhi",
    state: "Delhi",
    country: "India",
    rating: 4.9,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKoPAk1dQIbfYi9Yz-M0ozGClJiqh7EjE40bubJ85zMg&s=10"
  },

  {
    id: 212,
    brand: "Porsche",
    model: "911 Carrera",
    year: "(2024)",
    price: "1.85 Cr",
    mileage: 4200,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Coupe",
    color: "Yellow",
    engine: "3.0L Twin Turbo",
    horsepower: 379,
    seats: 4,
    doors: 2,
    location: "Mumbai",
    state: "Maharashtra",
    country: "India",
    rating: 5.0,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80"
  },

  {
    id: 213,
    brand: "Lamborghini",
    model: "Huracan",
    year: "(2022)",
    price: "32.6 Lakh",
    mileage: 3200,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Coupe",
    color: "Orange",
    engine: "5.2L V10",
    horsepower: 631,
    seats: 2,
    doors: 2,
    location: "Bangalore",
    state: "Karnataka",
    country: "India",
    rating: 5.0,
    isAvailable: false,
    isFeatured: true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5fN9cRHlU1FLsXSzOggHJi_Nbku563ONolZvAhqvNMA&s=10"
  },

  {
    id: 214,
    brand: "Ferrari",
    model: "Roma",
    year: "(2023)",
    price: "39 Lakh",
    mileage: 2700,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Coupe",
    color: "Red",
    engine: "3.9L V8",
    horsepower: 612,
    seats: 4,
    doors: 2,
    location: "Pune",
    state: "Maharashtra",
    country: "India",
    rating: 4.9,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&w=1200&q=80"
  },

  {
    id: 215,
    brand: "Volvo",
    model: "XC90",
    year: "(2024)",
    price: "78 Lakh",
    mileage: 7800,
    fuelType: "Hybrid",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Grey",
    engine: "2.0L Hybrid",
    horsepower: 455,
    seats: 7,
    doors: 5,
    location: "Hyderabad",
    state: "Telangana",
    country: "India",
    rating: 4.8,
    isAvailable: true,
    isFeatured: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhyFbuj21Aw5qyaFaapd_LzI9HnL4Ua7FXvGvDrDX9WQ&s=10"
  },

  {
    id: 216,
    brand: "Jeep",
    model: "Wrangler",
    year: "(2023)",
    price: "68 Lakh",
    mileage: 11200,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Green",
    engine: "2.0L Turbo",
    horsepower: 270,
    seats: 5,
    doors: 5,
    location: "Chandigarh",
    state: "Chandigarh",
    country: "India",
    rating: 4.7,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrx7ZyP0tnlDWFqpgHwgjrlc-Dq4s3WmygCmaZo2NqfA&s=10"
  },

  {
    id: 217,
    brand: "Volkswagen",
    model: "Golf GTI",
    year: "(2023)",
    price: "3.9 Cr",
    mileage: 9400,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Hatchback",
    color: "White",
    engine: "2.0L Turbo",
    horsepower: 241,
    seats: 5,
    doors: 5,
    location: "Delhi",
    state: "Delhi",
    country: "India",
    rating: 4.6,
    isAvailable: true,
    isFeatured: false,
    image:
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80"
  },

  {
    id: 218,
    brand: "Skoda",
    model: "Kodiaq",
    year: "(2024)",
    price: "25 Lakh",
    mileage: 6800,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Black",
    engine: "2.0L TSI",
    horsepower: 188,
    seats: 7,
    doors: 5,
    location: "Chandigarh",
    state: "Chandigarh",
    country: "India",
    rating: 4.7,
    isAvailable: true,
    isFeatured: false,
    image:
      "https://imgd.aeplcdn.com/664x374/n/cw/ec/158729/kodiaq-exterior-right-front-three-quarter-14.png?isig=0&q=80"
  },

  {
    id: 219,
    brand: "Tata",
    model: "Safari",
    year: "(2024)",
    price: "15 Lakh",
    mileage: 7200,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Black",
    engine: "2.0L Diesel",
    horsepower: 168,
    seats: 7,
    doors: 5,
    location: "Mohali",
    state: "Punjab",
    country: "India",
    rating: 4.6,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtTeWN5L8tKdASAp090vdGiZUsQHbAoPxZu1-1M_fhnA&s=10"
  },

  {
    id: 220,
    brand: "Mahindra",
    model: "Scorpio-N",
    year: "(2024)",
    price: "24.5 Lakh",
    mileage: 8500,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Black",
    engine: "2.2L Diesel",
    horsepower: 172,
    seats: 7,
    doors: 5,
    location: "Mohali",
    state: "Punjab",
    country: "India",
    rating: 4.8,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://stimg.cardekho.com/images/carexteriorimages/930x620/Mahindra/Scorpio-N/13740/1785926288341/front-left-side-47.jpg?tr=w-420"
  }
];
